{"name": "test_login[login1]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因：账号不正确\nassert False", "trace": "self = <test_zxj.Homework.test_cal.TestLogin object at 0x000001872CC6CAC8>, login = False\n\n    def test_login(self,login):\n        a = login\n        print(\"返回值%s\"%a)\n>       assert a,\"失败原因：账号不正确\"\nE       AssertionError: 失败原因：账号不正确\nE       assert False\n\ntest_cal.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "77d7a13e-5db5-4891-b85a-282ca434c9b5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "('zzz', 'jjj')"}], "start": 1594370457270, "stop": 1594370457270, "uuid": "fc558624-7f9a-40a1-8ec4-fe0f5bc50b41", "historyId": "934565262cd18427bbe2b8f3f61d696e", "testCaseId": "f53a883f3eec74aba65feaed76ab2c8a", "fullName": "test_cal.TestLogin#test_login", "labels": [{"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G8ROBTKO"}, {"name": "thread", "value": "34628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}